/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'build' at '5/21/14 2:17 PM' with Gradle 1.12
 *
 * @author build, @date 5/21/14 2:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
